# Generated by Django 3.0.5 on 2020-11-20 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20201120_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcommentmodel',
            old_name='mainComment',
            new_name='main_comment',
        ),
    ]
