# Generated by Django 3.0.5 on 2020-11-22 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20201122_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likemodel',
            name='likes',
        ),
    ]
