# Generated by Django 3.0.5 on 2020-11-30 09:58

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_likemodel_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='likemodel',
            name='date_time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='maincommentmodel',
            name='date_time_create',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 11, 30, 9, 58, 15, 116420, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postmodel',
            name='date_time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcommentmodel',
            name='date_time_create',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
